### PR TITLE
Pre-request hook for request mangling

### PR DESCRIPTION
**Pull request by j16sdiz**
See Issue #106 for details.

### CODE REVIEW

**Comment by marcosnils** [comment]
@j16sdiz I like this approach. Two comments

* Can you please add tests for it?
* Seems like Travis complained about the test, can you check?

Thx!.

**Comment by sschepens** [comment]
seems ok, could even be useful for some other things

**Comment by sschepens** [comment]
@j16sdiz could you add a test for this? maybe even the use case you're giving it

**Comment by j16sdiz** [comment]
I have added a test case.

**Comment by sschepens** [comment]
@marcosnils this seems ok, any comments?

**Comment by marcosnils** [comment]
@sschepens @j16sdiz :+1: merging.

**Comment by marcosnils** [comment]
After merging I just think about something: 

Why not providing some way of hooking middleware functions that will be called before and after each request?. That way `goreq` can be extended with different middlewares to do different things such as authentication / logging / etc. 

I feel like we're missing something if we just give the ability to call a `before` function and not an `after` one/

**Comment by j16sdiz** [comment]
@marcosnils  Actually, I had considered adding an `interface` for more hooks, but that kind of interface is hard to change without breaking backward compatibility. Without a full usecase for other hooks, I just implemented what I need.

**Pull request merged**
