### PR TITLE
Request#AddCookie added

### PR DESCRIPTION
**Pull request by bfontaine**
See @marcosnils’ [comment here](https://github.com/franela/goreq/issues/77#issuecomment-76386986).

### CODE REVIEW

**Comment by marcosnils** [comment]
@bfontaine good job!. I was thinking that maybe we can make the method something like

```go
func (r Request) AddCookie(c *http.Cookie) Request {
	r.cookies = append(r.cookies, c)
        return r
}
```

This way we can keep making requests with a one-liner like this:

```go
res, err := Request{Uri:"someuri"}
                .AddCookie(&http.Cookie{})
                .Do()
```

What do you think?

**Comment by bfontaine** [comment]
That’s a good idea, and it could be used for `AddHeader` as well.

Go complains when I use dots at the beginning of a line, so you’d have to use this syntax instead:

```go
res, err := Request{Uri:"someuri"}.
       AddCookie(&http.Cookie{}).
       Do()
```

There’s also an issue with the original request. With `func (r Request) AddCookie(…) Request`, `r` is passed by value and thus the returned request is *not* the same as the original one. This means that the code below won’t work as expected (it won’t send the cookie):

```go
req := Request{Uri: "someuri"}
req.AddCookie(&http.Cookie{})
res, err := req.Do()
```

Because the cookie is added to a copy of `req`, one would need to do that instead:

```go
req := Request{Uri: "someuri"}
req = req.AddCookie(&http.Cookie{})
res, err := req.Do()
```

On the other hand, `func (r *Request) AddCookie(…) *Request` works in this case, but breaks the first code:

```go
res, err := Request{Uri:"someuri"}.
       AddCookie(&http.Cookie{}).
       Do()
```

Go complains: “cannot call pointer method on Request literal”.

**Comment by marcosnils** [comment]
@bfontaine you're correct. Let's go with your suggestion so we can have the best of both worlds :smile:

**Comment by bfontaine** [comment]
Done. Let me know if you think I should add more tests.

**Pull request merged**
