### PR TITLE
fix issue #116

### LINKED ISSUE #116: goreq.Request.Timeout behavior is different from http.Client.Timeout
http://play.golang.org/p/Fjv_Bf_UyH
hangs on ioutil.ReadAll

http://play.golang.org/p/TsXX5MyMC4
timeout works.

we have to override goreq.DefaultClient to set timeout flawlessly

### PR DESCRIPTION
**Pull request by pathletboy**
Is it easy way to fix #116?

### CODE REVIEW

**Comment by marcosnils** [comment]
@pathletboy haven't had the time look at it, but at a first glance tests are failing.

**Comment by pathletboy** [comment]
type *http.Client has no field or method Timeout in go1.2, go1.5.1 passed.

**Comment by sschepens** [comment]
@pathletboy this is not good, it adds yet another race condition to goreq. This is setting the default client's timeout. We have similar issues now, and i'm not happy about them.
If two requests were made concurrently then there is a chance that one would step over the previous value of timeout before the first request actually starts.

**Comment by marcosnils** [comment]
@sschepens we were already having race conditions with the previous timeout implementation. I've moved our strategy to golang default timeout method. This will be automatically resolves when / if we dedice what to do with current race conditions.

**Pull request closed without merging**
