### PR TITLE
remove unnecessary else block

### PR DESCRIPTION
**Pull request by rexposadas**

### CODE REVIEW

**Comment by rexposadas** [comment]
closes #99

**Comment by rexposadas** [comment]
Interesting. I'm using `go version go1.4.2 darwin/386` (the latest stable version) and `make test` passes. 

Should I also be running `make test` under a different version ?

**Comment by marcosnils** [comment]
@rexposadas I'm observing the same thing. Seems like for some reason it doesn't pass in circleci with tip version. I haven't had time to look into this I'll investigate later today. 

I guess the fastest way to proceed would be to fix the Go version to 1.4.2 in circleci and then investigate why it's not passing in tip

**Comment by marcosnils** [comment]
@rexposadas I've updated master branch with proper fixes to make tests pass in tip version. Can you please rebase your PR and update?

Thx!

**Pull request merged**
